package com.mindlinksoft.recruitment.mychat;


import java.util.List;

/**
 * Represents the Object to be Exported to the output file by the IO processor
 * Contains:
 *          - logging: information for user on operations that have been performed
 *          - Conversation: The (potentially) processed conversation, otherwise the original
 *          - Report: The report generated by the Reporter (should there be one)
 */
public class ObjectToExport {

    private List<String> logging;
    private Conversation conversationToExport;
    private Report report;

    protected ObjectToExport(Conversation processedConversation, Report report, List<String> logging){
        this.conversationToExport = processedConversation;
        this.report = report;
        this.logging = logging;
    }

    public List<String> getLogging() {
        return logging;
    }

    public void setLogging(List<String> logging) {
        this.logging = logging;
    }

    public Conversation getConversationToExport() {
        return conversationToExport;
    }

    public void setConversationToExport(Conversation conversationToExport) {
        this.conversationToExport = conversationToExport;
    }

    public Report getReport() {
        return report;
    }

    public void setReport(Report report) {
        this.report = report;
    }
}
